version: '3'
services:
  keycloak:
    image: ams-keycloak:latest
    # image: quay.io/keycloak/keycloak:23.0.3
    container_name: keycloak123
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: w65DKtEOa8
      # KC_HOSTNAME: 172.16.13.31
      # KC_HOSTNAME_PORT: 8080
      KEYCLOAK_FRONTEND_URL: https://b69d-118-70-171-220.ngrok-free.app
      # KC_HOSTNAME_STRICT_BACKCHANNEL: true
      # KC_HOSTNAME_STRICT: false
      # KC_HTTP_ENABLED: true
      # KC_FEATURES: token-exchange,admin-fine-grained-authz,preview
      KC_FEATURES: token-exchange,declarative-user-profile
      KC_DB: mysql
      KC_DB_URL: jdbc:mysql://172.16.10.105:3306/umematsu_keycloak2
      KC_DB_USERNAME: root
      KC_DB_PASSWORD: w65DKtEOa8
      # KC_DB_URL: jdbc:mysql://stg-ams-db-instance-1.cczy0rgqlowe.ap-northeast-1.rds.amazonaws.com/umematsu_keycloak
      # KC_DB_USERNAME: admin
      # KC_DB_PASSWORD: 0j7YoRqL9w2N8qp
      KC_LOG_LEVEL: info
    # command: start-dev --hostname-url=https://b69d-118-70-171-220.ngrok-free.app
    command: ["start-dev", "--http-enabled=true", "--http-relative-path=/auth", "--http-port=8080", "--hostname-strict=false", "--hostname-strict-https=false", "--hostname-url=https://b69d-118-70-171-220.ngrok-free.app"]
    # command: ["start-dev", "--http-enabled=true", "--http-port=8080", "--hostname-strict=false", "--hostname-strict-https=false", "--hostname-url=https://b69d-118-70-171-220.ngrok-free.app"]